#pragma once

#include <QString>

struct TacticalEvent
{
    QString eventId;
    QString runId;
    QString puzzleId;
    QString sourceGameId;
    QString openingFamily;
    QString gamePhase;
    QString solutionSummary;
    QString sideToMove;
    QString materialBalance;
    QString kingSafetyState;
    QString pieceActivity;
    QString keyWeakness;
    QString kingExposureType;
    QString kingExposureSeverity;
    int loosePieceCount = 0;
    QString loosePieceSummary;
    int overloadedDefenderCount = 0;
    QString overloadedDefenderSummary;
    QString backRankState;
    QString luftState;
    QString kingLinePressureType;
    QString kingSquarePressureType;
    QString criticalPieceImbalanceSummary;
    QString structuralFeatureSummary;
    QString structuralFeatureConfidence;
    QString kingZoneTargetType;
    QString kingZoneTargetSummary;
    QString vulnerablePieceTargetType;
    QString vulnerablePieceTargetSummary;
    QString pressureLaneTargetType;
    QString pressureLaneTargetSummary;
    QString decisiveImbalanceTarget;
    QString pinnedCriticalPieceType;
    QString pinnedCriticalPieceSummary;
    QString defenderRemovalExposureType;
    QString defenderRemovalExposureSummary;
    QString kingColorComplexState;
    QString kingColorComplexSummary;
    QString targetZoneImbalanceType;
    QString targetZoneImbalanceSummary;
    QString structuralV2Summary;
    QString structuralV2Confidence;
    QString escapeGeometryState;
    QString escapeGeometrySummary;
    QString flightControlType;
    QString flightControlSummary;
    QString defensiveEscapeFragilityType;
    QString defensiveEscapeFragilitySummary;
    QString structuralV3Summary;
    QString structuralV3Confidence;
    QString attackerCoordinationType;
    QString attackerCoordinationSummary;
    QString defensiveNetworkFragilityType;
    QString defensiveNetworkFragilitySummary;
    QString structuralV4Summary;
    QString structuralV4Confidence;
    QString localTargetSummary;
    QString localTargetConfidence;
    QString triggerEvent;
    QString playerRatingRange;
    QString mappingStatus;
    int mappedStartPly = 0;
    QString mappingMethod;
    QString mappingConfidence;
    QString mappingNotes;
    int analysisWindowStartPly = 0;
    int analysisWindowEndPly = 0;
    int primaryBreakPly = 0;
    QString primaryBreakReason;
    QString retainedBreakFormatVersion;
    QString retainedBreakRole;
    QString retainedBreakPlayedMove;
    QString retainedBreakBestMove;
    QString retainedBreakCompactSequence;
    QString retainedBreakSummary;
    QString bestVsPlayedDivergenceSummary;
    QString divergenceType;
    QString divergenceSeverity;
    QString divergenceCompactSummary;
    QString divergenceEvidenceNotes;
    QString localSequenceConfidence;
    QString collapseSequenceFormatVersion;
    QString collapseSequenceType;
    QString collapseSequenceSummary;
    QString retainedRoleSummary;
    int omittedAdjacentCandidateCount = 0;
    QString omissionReasonSummary;
    QString omissionReasonCountsJson;
    QString engineLimitSummary;
    QString tacticalCandidatesJson;
    QString structuralCandidatesJson;
    QString evidencePayloadJson;
    QString assistantInferenceStatus;
    QString assistantLabelsJson;
    QString assistantSummaryMarkdown;
};
